# Generated by Django 5.2.1 on 2025-05-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='description',
            field=models.CharField(default='no description yet', max_length=300),
        ),
    ]
