# Generated by Django 5.2.1 on 2025-05-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_chaivariety_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chaivariety',
            name='reviewrating',
            field=models.FloatField(default=0.0),
        ),
    ]
