# Generated by Django 5.2.1 on 2025-05-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0003_chaivariety_ingredients_chaivariety_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=6),
            preserve_default=False,
        ),
    ]
