# Generated by Django 5.2.1 on 2025-06-05 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0005_chaireview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaivariety',
            name='description',
            field=models.CharField(default='no description yet'),
        ),
    ]
